export const capacityTable = {
    'unit': {
        // 基本公制
        'liter': { offset: 0, scale: 1 },
        'milliliter': { offset: 0, scale: 0.001 },
        'deciliter': { offset: 0, scale: 0.1 },
        'hectoliter': { offset: 0, scale: 100 },

        // 立方單位
        'cubic_meter': { offset: 0, scale: 1000 },
        'cubic_centimeter': { offset: 0, scale: 0.001 },
        'cubic_millimeter': { offset: 0, scale: 0.000001 },
        'cubic_inch': { offset: 0, scale: 0.016387064 },
        'cubic_foot': { offset: 0, scale: 28.316846592 },
        'cubic_yard': { offset: 0, scale: 764.554857984 },

        // 美制液體
        'us_gallon': { offset: 0, scale: 3.785411784 },
        'us_quart': { offset: 0, scale: 0.946352946 },
        'us_pint': { offset: 0, scale: 0.473176473 },
        'us_cup': { offset: 0, scale: 0.236588236 },
        'us_fluid_ounce': { offset: 0, scale: 0.02957353 },
        'us_tablespoon': { offset: 0, scale: 0.014786765 },
        'us_teaspoon': { offset: 0, scale: 0.004928922 },

        // 英制液體
        'uk_gallon': { offset: 0, scale: 4.54609 },
        'uk_quart': { offset: 0, scale: 1.13652 },
        'uk_pint': { offset: 0, scale: 0.568261 },
        'uk_cup': { offset: 0, scale: 0.284131 },
        'uk_fluid_ounce': { offset: 0, scale: 0.0284131 },
        'uk_tablespoon': { offset: 0, scale: 0.0142065 },
        'uk_teaspoon': { offset: 0, scale: 0.0047355 },

        // 工業
        'barrel': { offset: 0, scale: 158.987294928 },
    },
    'language': {
        'zh-TW': {
            'liter': 'L (公升)',
            'milliliter': 'ml (毫升)',
            'deciliter': 'dl (分升)',
            'hectoliter': 'hl (百升)',
            'cubic_meter': 'm³ (立方米)',
            'cubic_centimeter': 'cm³ (立方公分)',
            'cubic_millimeter': 'mm³ (立方毫米)',
            'cubic_inch': 'in³ (立方英寸)',
            'cubic_foot': 'ft³ (立方英尺)',
            'cubic_yard': 'yd³ (立方碼)',
            'us_gallon': 'gal (美制加侖)',
            'us_quart': 'qt (美制夸脫)',
            'us_pint': 'pt (美制品脫)',
            'us_cup': 'cup (美制杯)',
            'us_fluid_ounce': 'fl oz (美制液體盎司)',
            'us_tablespoon': 'tbsp (美制湯匙)',
            'us_teaspoon': 'tsp (美制茶匙)',
            'uk_gallon': 'gal (英制加侖)',
            'uk_quart': 'qt (英制夸脫)',
            'uk_pint': 'pt (英制品脫)',
            'uk_cup': 'cup (英制杯)',
            'uk_fluid_ounce': 'fl oz (英制液體盎司)',
            'uk_tablespoon': 'tbsp (英制湯匙)',
            'uk_teaspoon': 'tsp (英制茶匙)',
            'barrel': 'bbl (桶-石油)',
        },
        'en': {
            'liter': 'L (liter)',
            'milliliter': 'ml (milliliter)',
            'deciliter': 'dl (deciliter)',
            'hectoliter': 'hl (hectoliter)',
            'cubic_meter': 'm³ (cubic meter)',
            'cubic_centimeter': 'cm³ (cubic centimeter)',
            'cubic_millimeter': 'mm³ (cubic millimeter)',
            'cubic_inch': 'in³ (cubic inch)',
            'cubic_foot': 'ft³ (cubic foot)',
            'cubic_yard': 'yd³ (cubic yard)',
            'us_gallon': 'gal (US gallon)',
            'us_quart': 'qt (US quart)',
            'us_pint': 'pt (US pint)',
            'us_cup': 'cup (US cup)',
            'us_fluid_ounce': 'fl oz (US fluid ounce)',
            'us_tablespoon': 'tbsp (US tablespoon)',
            'us_teaspoon': 'tsp (US teaspoon)',
            'uk_gallon': 'gal (UK gallon)',
            'uk_quart': 'qt (UK quart)',
            'uk_pint': 'pt (UK pint)',
            'uk_cup': 'cup (UK cup)',
            'uk_fluid_ounce': 'fl oz (UK fluid ounce)',
            'uk_tablespoon': 'tbsp (UK tablespoon)',
            'uk_teaspoon': 'tsp (UK teaspoon)',
            'barrel': 'bbl (barrel)',
        },
    },
}


